{{- if and .Values.site24x7Agent.create .Values.site24x7Agent.leaseAPI.enabled }}
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: {{ include "site24x7Agent.name" . }}
  labels:
    {{- include "site24x7Agent.labels" . | nindent 4 }}
spec:
  holderIdentity: {{ printf "%s-pod" (include "site24x7Agent.name" .) | quote }}
  leaseDurationSeconds: {{ .Values.site24x7Agent.leaseAPI.leaseDurationSeconds }}
  leaseTransitions: 0
  acquireTime: {{ now | date "2006-01-02T15:04:05.000000Z" | quote }}
  renewTime: {{ now | date "2006-01-02T15:04:05.000000Z" | quote }}
{{- end }}
