{{- if and .Values.openShift (not .Values.site24x7Agent.applyNonRootSecurityContext) }}
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities:
- NET_BIND_SERVICE
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
kind: SecurityContextConstraints
metadata:
  name: {{ include "site24x7.fullname" . }}
priority: null
readOnlyRootFilesystem: false
seccompProfiles:
- '*'
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
  seLinuxOptions:
    user: "system_u"
    role: "system_r"
    type: "spc_t"
    level: "s0"
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{ include "site24x7.serviceAccountName" }}:{{ .Release.Namespace }}
volumes:
- configMap
- csi
- downwardAPI
- emptyDir
- ephemeral
- persistentVolumeClaim
- projected
- secret
- hostPath
{{- end }}